name: Deploy Springboot APÏ

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2d
    - uses: akhileshns/heroku-deploy@v3.12.12 # Deploy to heroku action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_API_EMAIL}}
        branch: main
        appdir: server
